export const workbookTabs = {
  parents: "01_Parent_Master",
  children: "02_Child_Master",
  schools: "03_School_Master",
  ageGroups: "04_Age_Group_Master",
  languages: "04_Language_Master",
  grades: "04_Grade_Master",
  skills: "05_Skill_Master",
  passions: "06_Passion_Master",
  questions: "07_Question_Master",
  questionOptions: "08_Question_Options",
  assessments: "12_Child_Assessments",
  responses: "13_Child_Responses",
  skillScores: "14_Child_Skill_Scores",
  childPassions: "15_Child_Passions",
  configuration: "20_App_Configuration",
} as const;
